title: Singa Shravanti
logo: assets/css/IMG_20250415_214733.jpg
description: Tech Enthusiast | Future Software Developer | Passionate about Java
show_downloads: false
google analytics:
theme: jekyll-theme-minimal




